# Generated by Django 4.1.4 on 2023-01-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIrstname', models.CharField(max_length=50)),
                ('LAstname', models.CharField(max_length=50)),
                ('EMail', models.EmailField(max_length=50)),
                ('COmpany', models.CharField(max_length=50)),
                ('LOcation', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
