# Generated by Django 4.1.4 on 2023-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_details_delete_empdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
