# Generated by Django 4.1.4 on 2023-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_details_address_alter_details_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
